-- Live-safe subcategory image path patch.
-- Upload public/uploads/subcategories/* to the same path on live before running this.
-- It only fills blank image_path values and leaves existing custom images untouched.
START TRANSACTION;
UPDATE subcategories SET image_path = 'uploads/subcategories/46-baby-food.svg' WHERE id = 46 AND subcategory_name = 'Baby Food' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/47-baby-bath-and-shampoo.svg' WHERE id = 47 AND subcategory_name = 'Baby Bath & Shampoo' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/48-diapers-and-wipes.svg' WHERE id = 48 AND subcategory_name = 'Diapers & Wipes' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/49-baby-lotion-and-cream.svg' WHERE id = 49 AND subcategory_name = 'Baby Lotion & Cream' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/50-baby-powder.svg' WHERE id = 50 AND subcategory_name = 'Baby Powder' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/51-feeding-bottles.svg' WHERE id = 51 AND subcategory_name = 'Feeding Bottles' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/52-baby-accessories.svg' WHERE id = 52 AND subcategory_name = 'Baby Accessories' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/53-baby-health-and-safety.svg' WHERE id = 53 AND subcategory_name = 'Baby Health & Safety' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/54-floor-cleaners.svg' WHERE id = 54 AND subcategory_name = 'Floor Cleaners' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/55-bathroom-cleaners.svg' WHERE id = 55 AND subcategory_name = 'Bathroom Cleaners' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/56-kitchen-cleaners.svg' WHERE id = 56 AND subcategory_name = 'Kitchen Cleaners' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/57-dishwash-liquids.svg' WHERE id = 57 AND subcategory_name = 'Dishwash Liquids' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/58-scrub-pads-and-brushes.svg' WHERE id = 58 AND subcategory_name = 'Scrub Pads & Brushes' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/59-laundry-detergents.svg' WHERE id = 59 AND subcategory_name = 'Laundry Detergents' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/60-fabric-conditioners.svg' WHERE id = 60 AND subcategory_name = 'Fabric Conditioners' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/61-air-fresheners.svg' WHERE id = 61 AND subcategory_name = 'Air Fresheners' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/62-cleaning-tools.svg' WHERE id = 62 AND subcategory_name = 'Cleaning Tools' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/63-chocolate-cookies.svg' WHERE id = 63 AND subcategory_name = 'Chocolate Cookies' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/64-butter-cookies.svg' WHERE id = 64 AND subcategory_name = 'Butter Cookies' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/65-healthy-cookies.svg' WHERE id = 65 AND subcategory_name = 'Healthy Cookies' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/66-cream-biscuits.svg' WHERE id = 66 AND subcategory_name = 'Cream Biscuits' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/67-sugar-free-cookies.svg' WHERE id = 67 AND subcategory_name = 'Sugar-Free Cookies' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/68-oats-cookies.svg' WHERE id = 68 AND subcategory_name = 'Oats Cookies' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/69-dry-fruit-cookies.svg' WHERE id = 69 AND subcategory_name = 'Dry Fruit Cookies' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/70-kids-cookies.svg' WHERE id = 70 AND subcategory_name = 'Kids Cookies' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/71-milk.svg' WHERE id = 71 AND subcategory_name = 'Milk' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/72-curd-and-yogurt.svg' WHERE id = 72 AND subcategory_name = 'Curd & Yogurt' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/73-butter-and-cheese.svg' WHERE id = 73 AND subcategory_name = 'Butter & Cheese' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/74-paneer.svg' WHERE id = 74 AND subcategory_name = 'Paneer' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/75-fresh-bread.svg' WHERE id = 75 AND subcategory_name = 'Fresh Bread' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/76-buns-and-pav.svg' WHERE id = 76 AND subcategory_name = 'Buns & Pav' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/77-brown-bread.svg' WHERE id = 77 AND subcategory_name = 'Brown Bread' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/78-eggs.svg' WHERE id = 78 AND subcategory_name = 'Eggs' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/79-dairy-beverages.svg' WHERE id = 79 AND subcategory_name = 'Dairy Beverages' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/80-frozen-vegetables.svg' WHERE id = 80 AND subcategory_name = 'Frozen Vegetables' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/81-frozen-snacks.svg' WHERE id = 81 AND subcategory_name = 'Frozen Snacks' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/82-frozen-peas-and-corn.svg' WHERE id = 82 AND subcategory_name = 'Frozen Peas & Corn' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/83-ready-to-cook.svg' WHERE id = 83 AND subcategory_name = 'Ready to Cook' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/84-frozen-french-fries.svg' WHERE id = 84 AND subcategory_name = 'Frozen French Fries' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/85-frozen-paratha.svg' WHERE id = 85 AND subcategory_name = 'Frozen Paratha' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/86-frozen-seafood.svg' WHERE id = 86 AND subcategory_name = 'Frozen Seafood' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/87-frozen-meat.svg' WHERE id = 87 AND subcategory_name = 'Frozen Meat' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/88-fresh-fruits.svg' WHERE id = 88 AND subcategory_name = 'Fresh Fruits' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/89-fresh-vegetables.svg' WHERE id = 89 AND subcategory_name = 'Fresh Vegetables' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/90-leafy-vegetables.svg' WHERE id = 90 AND subcategory_name = 'Leafy Vegetables' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/91-exotic-fruits.svg' WHERE id = 91 AND subcategory_name = 'Exotic Fruits' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/92-exotic-vegetables.svg' WHERE id = 92 AND subcategory_name = 'Exotic Vegetables' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/93-organic-vegetables.svg' WHERE id = 93 AND subcategory_name = 'Organic Vegetables' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/94-herbs-and-seasonings.svg' WHERE id = 94 AND subcategory_name = 'Herbs & Seasonings' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/95-cut-and-packed-fruits.svg' WHERE id = 95 AND subcategory_name = 'Cut & Packed Fruits' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/96-hair-oil.svg' WHERE id = 96 AND subcategory_name = 'Hair Oil' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/97-shampoo.svg' WHERE id = 97 AND subcategory_name = 'Shampoo' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/98-conditioner.svg' WHERE id = 98 AND subcategory_name = 'Conditioner' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/99-hair-serum.svg' WHERE id = 99 AND subcategory_name = 'Hair Serum' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/100-hair-color.svg' WHERE id = 100 AND subcategory_name = 'Hair Color' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/101-hair-gel-and-wax.svg' WHERE id = 101 AND subcategory_name = 'Hair Gel & Wax' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/102-hair-masks.svg' WHERE id = 102 AND subcategory_name = 'Hair Masks' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/103-anti-dandruff-products.svg' WHERE id = 103 AND subcategory_name = 'Anti-Dandruff Products' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/104-family-packs.svg' WHERE id = 104 AND subcategory_name = 'Family Packs' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/105-cups-and-tubs.svg' WHERE id = 105 AND subcategory_name = 'Cups & Tubs' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/106-cones.svg' WHERE id = 106 AND subcategory_name = 'Cones' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/107-ice-cream-bars.svg' WHERE id = 107 AND subcategory_name = 'Ice Cream Bars' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/108-kulfi.svg' WHERE id = 108 AND subcategory_name = 'Kulfi' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/109-gelato.svg' WHERE id = 109 AND subcategory_name = 'Gelato' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/110-sugar-free-ice-cream.svg' WHERE id = 110 AND subcategory_name = 'Sugar-Free Ice Cream' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/111-kids-ice-cream.svg' WHERE id = 111 AND subcategory_name = 'Kids Ice Cream' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/112-kitchen-tools.svg' WHERE id = 112 AND subcategory_name = 'Kitchen Tools' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/113-storage-containers.svg' WHERE id = 113 AND subcategory_name = 'Storage Containers' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/114-cookware.svg' WHERE id = 114 AND subcategory_name = 'Cookware' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/115-dinner-sets.svg' WHERE id = 115 AND subcategory_name = 'Dinner Sets' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/116-water-bottles.svg' WHERE id = 116 AND subcategory_name = 'Water Bottles' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/117-home-utility.svg' WHERE id = 117 AND subcategory_name = 'Home Utility' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/118-disposable-products.svg' WHERE id = 118 AND subcategory_name = 'Disposable Products' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/119-cleaning-accessories.svg' WHERE id = 119 AND subcategory_name = 'Cleaning Accessories' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/120-almonds.svg' WHERE id = 120 AND subcategory_name = 'Almonds' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/121-cashews.svg' WHERE id = 121 AND subcategory_name = 'Cashews' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/122-pistachios.svg' WHERE id = 122 AND subcategory_name = 'Pistachios' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/123-walnuts.svg' WHERE id = 123 AND subcategory_name = 'Walnuts' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/124-mixed-nuts.svg' WHERE id = 124 AND subcategory_name = 'Mixed Nuts' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/125-raisins-and-dry-fruits.svg' WHERE id = 125 AND subcategory_name = 'Raisins & Dry Fruits' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/126-roasted-nuts.svg' WHERE id = 126 AND subcategory_name = 'Roasted Nuts' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/127-salted-nuts.svg' WHERE id = 127 AND subcategory_name = 'Salted Nuts' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/128-combo-offers.svg' WHERE id = 128 AND subcategory_name = 'Combo Offers' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/129-buy-1-get-1.svg' WHERE id = 129 AND subcategory_name = 'Buy 1 Get 1' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/130-discount-deals.svg' WHERE id = 130 AND subcategory_name = 'Discount Deals' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/131-festival-offers.svg' WHERE id = 131 AND subcategory_name = 'Festival Offers' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/132-clearance-sale.svg' WHERE id = 132 AND subcategory_name = 'Clearance Sale' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/133-daily-essentials-offers.svg' WHERE id = 133 AND subcategory_name = 'Daily Essentials Offers' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/134-weekend-specials.svg' WHERE id = 134 AND subcategory_name = 'Weekend Specials' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/135-top-savings.svg' WHERE id = 135 AND subcategory_name = 'Top Savings' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/136-bath-soap.svg' WHERE id = 136 AND subcategory_name = 'Bath Soap' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/137-body-wash.svg' WHERE id = 137 AND subcategory_name = 'Body Wash' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/138-face-wash.svg' WHERE id = 138 AND subcategory_name = 'Face Wash' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/139-skin-care.svg' WHERE id = 139 AND subcategory_name = 'Skin Care' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/140-oral-care.svg' WHERE id = 140 AND subcategory_name = 'Oral Care' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/141-deodorants.svg' WHERE id = 141 AND subcategory_name = 'Deodorants' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/142-feminine-hygiene.svg' WHERE id = 142 AND subcategory_name = 'Feminine Hygiene' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/143-grooming-products.svg' WHERE id = 143 AND subcategory_name = 'Grooming Products' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/144-basmati-rice.svg' WHERE id = 144 AND subcategory_name = 'Basmati Rice' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/145-raw-rice.svg' WHERE id = 145 AND subcategory_name = 'Raw Rice' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/146-millets.svg' WHERE id = 146 AND subcategory_name = 'Millets' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/147-wheat.svg' WHERE id = 147 AND subcategory_name = 'Wheat' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/148-flour.svg' WHERE id = 148 AND subcategory_name = 'Flour' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/149-dals-and-pulses.svg' WHERE id = 149 AND subcategory_name = 'Dals & Pulses' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/150-poha-and-vermicelli.svg' WHERE id = 150 AND subcategory_name = 'Poha & Vermicelli' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/151-organic-grains.svg' WHERE id = 151 AND subcategory_name = 'Organic Grains' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/152-chips-and-namkeen.svg' WHERE id = 152 AND subcategory_name = 'Chips & Namkeen' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/153-chocolates.svg' WHERE id = 153 AND subcategory_name = 'Chocolates' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/154-soft-drinks.svg' WHERE id = 154 AND subcategory_name = 'Soft Drinks' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/155-juices.svg' WHERE id = 155 AND subcategory_name = 'Juices' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/156-tea-and-coffee.svg' WHERE id = 156 AND subcategory_name = 'Tea & Coffee' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/157-energy-drinks.svg' WHERE id = 157 AND subcategory_name = 'Energy Drinks' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/158-instant-drinks.svg' WHERE id = 158 AND subcategory_name = 'Instant Drinks' AND (image_path IS NULL OR image_path = '');
UPDATE subcategories SET image_path = 'uploads/subcategories/159-healthy-snacks.svg' WHERE id = 159 AND subcategory_name = 'Healthy Snacks' AND (image_path IS NULL OR image_path = '');
COMMIT;
