<?php

return [
    'brand' => [
        'name' => 'Express Bazar Admin',
        'tagline' => 'Operations, catalog and location control',
    ],

    'stats' => [
        ['label' => 'Core Modules', 'value' => '25', 'note' => 'Ready to build out'],
        ['label' => 'Location Layers', 'value' => '3', 'note' => 'Country, city, zone'],
        ['label' => 'Inventory Modes', 'value' => '2', 'note' => 'Internal and EPOS'],
        ['label' => 'Workflow Focus', 'value' => 'Realtime', 'note' => 'Immediate updates'],
    ],

    'navigation' => [
        [
            'group' => 'Overview',
            'items' => [
                ['label' => 'Dashboard', 'route' => 'admin.dashboard', 'icon' => 'home', 'active' => 'dashboard'],
            ],
        ],
        [
            'group' => 'Master Data',
            'items' => [
                ['label' => 'Vendor Master', 'route' => 'admin.vendors.index', 'icon' => 'building-store', 'active' => 'vendors'],
                ['label' => 'Category Master', 'route' => 'admin.categories.index', 'icon' => 'category', 'active' => 'categories'],
                ['label' => 'Subcategory Master', 'route' => 'admin.subcategories.index', 'icon' => 'category-2', 'active' => 'subcategories'],
                ['label' => 'Customer Management', 'route' => 'admin.customers.index', 'icon' => 'users', 'active' => 'customers'],
                ['label' => 'Tax Master', 'route' => 'admin.taxes.index', 'icon' => 'receipt-2', 'active' => 'taxes'],
            ],
        ],
        [
            'group' => 'Location',
            'items' => [
                ['label' => 'Country Management', 'route' => 'admin.countries.index', 'icon' => 'world', 'active' => 'countries'],
                ['label' => 'City Management', 'route' => 'admin.cities.index', 'icon' => 'map-pin', 'active' => 'cities'],
                ['label' => 'Region / Zone', 'route' => 'admin.zones.index', 'icon' => 'map-2', 'active' => 'zones'],
            ],
        ],
        [
            'group' => 'Commerce',
            'items' => [
                ['label' => 'Product Management', 'route' => 'admin.products.index', 'icon' => 'shopping-bag', 'active' => 'products'],
                ['label' => 'Inventory Management', 'route' => 'admin.inventory.index', 'icon' => 'box-seam', 'active' => 'inventory'],
                ['label' => 'Order Management', 'route' => 'admin.orders.index', 'icon' => 'clipboard-list', 'active' => 'orders'],
                ['label' => 'Payment Management', 'route' => 'admin.payments.index', 'icon' => 'credit-card', 'active' => 'payments'],
                ['label' => 'Coupon Management', 'route' => 'admin.coupons.index', 'icon' => 'discount-2', 'active' => 'coupons'],
                ['label' => 'Delivery & Logistics', 'route' => 'admin.delivery.index', 'icon' => 'truck-delivery', 'active' => 'delivery'],
            ],
        ],
        [
            'group' => 'System',
            'items' => [
                ['label' => 'Notification Management', 'route' => 'admin.notifications.index', 'icon' => 'bell', 'active' => 'notifications'],
                ['label' => 'Reports & Analytics', 'route' => 'admin.reports.index', 'icon' => 'chart-bar', 'active' => 'reports'],
                ['label' => 'User & Role Management', 'route' => 'admin.roles.index', 'icon' => 'shield-lock', 'active' => 'roles'],
                ['label' => 'Admin Users', 'route' => 'admin.users.index', 'icon' => 'user-shield', 'active' => 'users'],
                ['label' => 'System Configuration', 'route' => 'admin.system-config.edit', 'icon' => 'settings', 'active' => 'config'],
            ],
        ],
    ],

    'modules' => [
        'vendors' => [
            'group' => 'Master Data',
            'title' => 'Vendor Master',
            'subtitle' => 'Manage vendors, inventory mode and EPOS settings.',
            'crud_route' => 'admin.vendors.index',
            'objective' => 'Manage vendors who sell products in the system.',
            'workflow' => [
                'Open Vendor Management and review the vendor list.',
                'Add a vendor with contact, address, country, city and zone.',
                'Set inventory mode to Internal or EPOS.',
                'If EPOS is selected, capture API URL, API key and credentials.',
            ],
            'fields' => ['Vendor Name', 'Email', 'Phone', 'Address', 'Country', 'City', 'Zone', 'Inventory Mode', 'API URL', 'API Key'],
            'rules' => ['Vendor must map to a zone.', 'Vendor must be active to sell.', 'EPOS vendors enable sync automatically.'],
            'database' => ['vendors', 'vendor_locations', 'vendor_epos_credentials'],
            'impact' => ['Inventory mode controls stock handling.', 'Active vendors can appear in the storefront.'],
        ],
        'categories' => [
            'group' => 'Master Data',
            'title' => 'Category Master',
            'subtitle' => 'Create top-level product categories.',
            'crud_route' => 'admin.categories.index',
            'objective' => 'Define top-level product categories.',
            'workflow' => [
                'Open Category Master.',
                'Review the category list and status.',
                'Add a unique category name and optional image.',
            ],
            'fields' => ['Category Name', 'Image', 'Status'],
            'rules' => ['Category name must be unique.', 'Used for product mapping.'],
            'database' => ['categories'],
            'impact' => ['Categories become available in product creation immediately.'],
        ],
        'subcategories' => [
            'group' => 'Master Data',
            'title' => 'Subcategory Master',
            'subtitle' => 'Create subcategories under categories.',
            'crud_route' => 'admin.subcategories.index',
            'objective' => 'Define subcategories under categories.',
            'workflow' => [
                'Open Subcategory Master.',
                'Choose a category and add the subcategory name.',
                'Save with the desired status.',
            ],
            'fields' => ['Category', 'Subcategory Name', 'Status'],
            'rules' => ['Must belong to a category.', 'Used in product classification.'],
            'database' => ['subcategories'],
            'impact' => ['Subcategories improve catalog filtering.'],
        ],
        'customers' => [
            'group' => 'Master Data',
            'title' => 'Customer Management',
            'subtitle' => 'View and control customer accounts.',
            'crud_route' => 'admin.customers.index',
            'objective' => 'Allow admin to manage customer accounts.',
            'workflow' => [
                'Open Customer Management.',
                'View customer list with status and created date.',
                'Open customer details for profile, address and order history.',
                'Activate or deactivate users when needed.',
            ],
            'fields' => ['Name', 'Email', 'Phone', 'Status', 'Created Date'],
            'rules' => ['Email is the primary identity.', 'Password should not be edited manually.'],
            'database' => ['customers', 'customer_addresses', 'customer_orders'],
            'impact' => ['Customer status controls storefront access.'],
        ],
        'taxes' => [
            'group' => 'Master Data',
            'title' => 'Tax Master',
            'subtitle' => 'Define tax rules and checkout calculations.',
            'crud_route' => 'admin.taxes.index',
            'objective' => 'Define tax rules for products.',
            'workflow' => [
                'Open Tax Master.',
                'Create a tax with percentage and optional region.',
                'Map the tax to products during product creation.',
            ],
            'fields' => ['Tax Name', 'Tax Percentage', 'Country / Region', 'Status'],
            'rules' => ['Tax must be valid and active.', 'Applied during checkout.'],
            'database' => ['taxes', 'product_taxes'],
            'impact' => ['Tax is included in the final payable amount.'],
        ],
        'countries' => [
            'group' => 'Location',
            'title' => 'Country Management',
            'subtitle' => 'Create countries for the location hierarchy.',
            'crud_route' => 'admin.countries.index',
            'objective' => 'Allow admin to define countries for multi-country operations.',
            'workflow' => [
                'Open Location Management > Country.',
                'View the country list with currency, status and created date.',
                'Add country, code, currency and optional timezone.',
            ],
            'fields' => ['Country Name', 'Country Code', 'Currency', 'Timezone', 'Status'],
            'rules' => ['Country name is mandatory.', 'Country code must be unique.', 'Only active countries are usable.'],
            'database' => ['countries'],
            'impact' => ['Used by city creation, vendor onboarding and customer selection.'],
        ],
        'cities' => [
            'group' => 'Location',
            'title' => 'City Management',
            'subtitle' => 'Create cities under a country.',
            'crud_route' => 'admin.cities.index',
            'objective' => 'Allow admin to create and manage cities under a country.',
            'workflow' => [
                'Open Location Management > City.',
                'Choose a country and add city details.',
                'Save and make the city available to zones, vendors and customers.',
            ],
            'fields' => ['Country', 'State / Province', 'City Name', 'City Code', 'Status'],
            'rules' => ['Country selection is mandatory.', 'City must be unique within a country.'],
            'database' => ['cities'],
            'impact' => ['Used by region / zone creation and vendor mapping.'],
        ],
        'zones' => [
            'group' => 'Location',
            'title' => 'Region / Zone Management',
            'subtitle' => 'Define serviceable delivery areas.',
            'crud_route' => 'admin.zones.index',
            'objective' => 'Allow admin to define delivery zones under a city.',
            'workflow' => [
                'Open Location Management > Region / Zone.',
                'Select country and city, then define zone and postcode.',
                'Set delivery availability and save.',
            ],
            'fields' => ['Country', 'City', 'Zone Name', 'Zone Code', 'Delivery Available', 'Status'],
            'rules' => ['City is mandatory.', 'Zone code must be unique within a city.', 'Inactive zones should not be selectable.'],
            'database' => ['regions_zones', 'delivery_config'],
            'impact' => ['Controls delivery availability and product visibility.'],
        ],
        'products' => [
            'group' => 'Commerce',
            'title' => 'Product Management',
            'subtitle' => 'Create catalog items with pricing and discounts.',
            'crud_route' => 'admin.products.index',
            'objective' => 'Create and manage products, mapping them to vendors and inventory mode.',
            'workflow' => [
                'Open Product Management.',
                'Select vendor, category and subcategory.',
                'Configure pricing, discount and stock settings.',
                'Save so the product is available immediately.',
            ],
            'fields' => ['Product Name', 'Description', 'Category', 'Subcategory', 'Vendor', 'Price', 'Discount', 'Final Price', 'Inventory Mode', 'Stock Quantity'],
            'rules' => ['Product must belong to a vendor.', 'Discount cannot exceed price.', 'EPOS stock is read-only.'],
            'database' => ['products', 'product_inventory'],
            'impact' => ['Product visibility depends on vendor, zone and stock.'],
        ],
        'inventory' => [
            'group' => 'Commerce',
            'title' => 'Inventory Management',
            'subtitle' => 'Track stock for internal and EPOS inventory.',
            'crud_route' => 'admin.inventory.index',
            'objective' => 'Manage and monitor product inventory for all vendors.',
            'workflow' => [
                'Open Inventory Management.',
                'View internal or EPOS stock levels.',
                'Adjust internal stock or sync EPOS stock.',
            ],
            'fields' => ['Product Name', 'Vendor Name', 'Inventory Mode', 'Current Stock', 'Unit', 'Last Updated', 'Sync Status'],
            'rules' => ['Internal stock can be edited.', 'EPOS stock is read-only.', 'Stock cannot go below zero.'],
            'database' => ['product_inventory', 'inventory_logs'],
            'impact' => ['Inventory changes reflect immediately in product and order flows.'],
        ],
        'orders' => [
            'group' => 'Commerce',
            'title' => 'Order Management',
            'subtitle' => 'Track the full order lifecycle.',
            'crud_route' => 'admin.orders.index',
            'objective' => 'Manage the complete order lifecycle from placement to completion.',
            'workflow' => [
                'Open Order Management.',
                'Review order list and details.',
                'Move orders through pending, accepted, processing, dispatched, delivered and completed.',
            ],
            'fields' => ['Order ID', 'Customer', 'Vendor', 'Zone', 'Total Amount', 'Payment Status', 'Order Status', 'Order Date'],
            'rules' => ['Stock must be validated before order creation.', 'Cannot dispatch without acceptance.'],
            'database' => ['orders', 'order_items', 'order_status_history'],
            'impact' => ['Order status updates are reflected across customer and vendor screens.'],
        ],
        'payments' => [
            'group' => 'Commerce',
            'title' => 'Payment Management',
            'subtitle' => 'Track transactions and refunds.',
            'crud_route' => 'admin.payments.index',
            'objective' => 'Manage and monitor all payment transactions.',
            'workflow' => [
                'Open Payment Management.',
                'Review gateway responses and payment logs.',
                'Process refunds when necessary.',
            ],
            'fields' => ['Transaction ID', 'Order ID', 'Payment Method', 'Amount', 'Status', 'Gateway Response', 'Timestamp'],
            'rules' => ['Online payments must be verified before confirmation.', 'Duplicate transactions must be prevented.'],
            'database' => ['payments', 'payment_logs'],
            'impact' => ['Payment status syncs with order status instantly.'],
        ],
        'coupons' => [
            'group' => 'Commerce',
            'title' => 'Coupon Management',
            'subtitle' => 'Create checkout coupons and vendor-specific offers.',
            'crud_route' => 'admin.coupons.index',
            'objective' => 'Allow admins to create coupon codes that customers can apply during checkout.',
            'workflow' => [
                'Open Coupon Management.',
                'Create a coupon with code, discount type, value and optional minimum order.',
                'Optionally restrict the coupon to one vendor and expiry date.',
            ],
            'fields' => ['Code', 'Type', 'Value', 'Minimum Order', 'Vendor', 'Expiry Date', 'Status'],
            'rules' => ['Coupon code must be unique.', 'Only active and unexpired coupons apply at checkout.', 'Only one coupon can be used per order.'],
            'database' => ['coupons'],
            'impact' => ['Customer checkout totals update when a valid coupon is applied.'],
        ],
        'delivery' => [
            'group' => 'Commerce',
            'title' => 'Delivery & Logistics',
            'subtitle' => 'Control delivery availability and charges.',
            'crud_route' => 'admin.delivery.index',
            'objective' => 'Manage delivery configuration and order fulfillment.',
            'workflow' => [
                'Open Delivery & Logistics.',
                'Set delivery availability for a country, city and zone.',
                'Assign delivery charges and track order dispatch.',
            ],
            'fields' => ['Country', 'City', 'Zone', 'Delivery Available', 'Delivery Charge', 'Dispatch Status'],
            'rules' => ['Delivery must be mapped to a zone.', 'Cannot dispatch before acceptance.'],
            'database' => ['delivery_config', 'delivery_logs'],
            'impact' => ['Checkout blocks immediately when delivery is unavailable.'],
        ],
        'notifications' => [
            'group' => 'System',
            'title' => 'Notification Management',
            'subtitle' => 'Template-based notifications for events.',
            'crud_route' => 'admin.notifications.index',
            'objective' => 'Manage system-generated notifications for customers, vendors and admins.',
            'workflow' => [
                'Open Notification Management.',
                'Create templates for order, payment and delivery events.',
                'Track sent and failed notifications in logs.',
            ],
            'fields' => ['Template Name', 'Type', 'Channel', 'Subject', 'Message Body', 'Status'],
            'rules' => ['Templates must be active.', 'Placeholders must be valid.'],
            'database' => ['notification_templates', 'notification_logs'],
            'impact' => ['Notifications fire automatically from system events.'],
        ],
        'reports' => [
            'group' => 'System',
            'title' => 'Reports & Analytics',
            'subtitle' => 'Real-time business reporting.',
            'crud_route' => 'admin.reports.index',
            'objective' => 'Provide admin with real-time insights into system performance.',
            'workflow' => [
                'Open Reports & Analytics.',
                'View summary metrics and breakdowns.',
                'Filter by vendor, location, date and status.',
            ],
            'fields' => ['Total Orders', 'Total Revenue', 'Vendor Performance', 'Inventory Status', 'Order Status', 'Location Revenue'],
            'rules' => ['Filters must stay consistent.', 'Reports must reflect live data.'],
            'database' => ['orders', 'products', 'vendors', 'inventory', 'regions_zones'],
            'impact' => ['Supports operational decisions and exportable snapshots.'],
        ],
        'roles' => [
            'group' => 'System',
            'title' => 'User & Role Management',
            'subtitle' => 'Role-based access control for admin users.',
            'crud_route' => 'admin.roles.index',
            'objective' => 'Manage admin users and access permissions.',
            'workflow' => [
                'Open User & Role Management.',
                'Create roles and assign permissions.',
                'Create users and bind them to roles.',
            ],
            'fields' => ['Role Name', 'Permissions', 'User Name', 'Email', 'Username', 'Password', 'Status'],
            'rules' => ['Every user must have a role.', 'Email and username must be unique.'],
            'database' => ['users', 'roles', 'role_permissions', 'audit_logs'],
            'impact' => ['Menu access changes immediately after role updates.'],
        ],
        'users' => [
            'group' => 'System',
            'title' => 'Admin User Management',
            'subtitle' => 'Create backend users and assign roles.',
            'crud_route' => 'admin.users.index',
            'objective' => 'Create admin users and assign a role for access control.',
            'workflow' => [
                'Open Admin Users.',
                'Create a backend user with name, email, phone, role and password.',
                'Update or deactivate the user when access changes.',
            ],
            'fields' => ['Name', 'Email', 'Phone', 'Role', 'Status', 'Password'],
            'rules' => ['Role must exist.', 'Password is required when creating a user.'],
            'database' => ['users'],
            'impact' => ['Admin users can sign in and inherit their assigned role permissions.'],
        ],
        'config' => [
            'group' => 'System',
            'title' => 'System Configuration',
            'subtitle' => 'Global settings and feature controls.',
            'crud_route' => 'admin.system-config.edit',
            'objective' => 'Provide centralized control for application-wide settings.',
            'workflow' => [
                'Open System Configuration.',
                'Set brand, location, order and payment settings.',
                'Save once to apply changes immediately across the app.',
            ],
            'fields' => ['Application Name', 'Company Name', 'Address', 'Support Email', 'Support Phone', 'Default Country', 'Default City', 'Feature Toggles'],
            'rules' => ['Only authorized users can edit config.', 'Critical settings must be validated before save.'],
            'database' => ['system_config'],
            'impact' => ['Affects storefront, checkout, notifications and inventory.'],
        ],
    ],
];
